name: TryHackMe Update Badge
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: Update TryHackMe badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download badge
        run: |
          curl -o assets/thm_propic.png "https://tryhackme-badges.s3.amazonaws.com/liz.mclaughlin.png"
      - name: Commit and push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add assets/thm_propic.png
          git commit -m "Updated TryHackMe badge" || echo "No changes to commit"
          git push
